# Generated by Django 2.2.4 on 2022-10-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20221004_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
    ]
