# Generated by Django 2.2.4 on 2022-09-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='notes',
            field=models.TextField(default='The Publisher is Dead !'),
        ),
    ]
